# Generated by Django 5.0.14 on 2026-05-28 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autoplay_interval', models.PositiveIntegerField(default=5000, help_text='Tempo entre cada slide em milissegundos (5000 = 5s)', verbose_name='Intervalo automático (ms)')),
                ('transition_speed', models.PositiveIntegerField(default=800, help_text='Duração da animação entre slides', verbose_name='Velocidade da transição (ms)')),
            ],
            options={
                'verbose_name': 'Configuração do Carrossel',
                'verbose_name_plural': 'Configurações do Carrossel',
            },
        ),
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text='Ex: "Nova Coleção", "Ofertas"', max_length=100, verbose_name='Rótulo')),
                ('title', models.CharField(blank=True, help_text='Ex: "Camisas de Time"', max_length=200, verbose_name='Título')),
                ('title_highlight', models.CharField(blank=True, help_text='Parte do título com cor de destaque. Ex: "Brasil"', max_length=200, verbose_name='Título em destaque')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='URL da Imagem')),
                ('link_url', models.CharField(blank=True, help_text='Ex: /catalog/camisas-time/ ou deixe vazio para /', max_length=200, verbose_name='URL do Link')),
                ('link_text', models.CharField(default='Ver Agora', max_length=100, verbose_name='Texto do Botão')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Slide do Carrossel',
                'verbose_name_plural': 'Slides do Carrossel',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(verbose_name='Descrição')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('promotional_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Promocional')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='Imagem')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Estoque')),
                ('available', models.BooleanField(default=True, verbose_name='Disponível')),
                ('featured', models.BooleanField(default=False, verbose_name='Destaque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='catalog.category', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='catalog_pro_slug_2b1eb6_idx'), models.Index(fields=['-created_at'], name='catalog_pro_created_eee82f_idx')],
            },
        ),
    ]
