# Generated by Django 5.0.14 on 2026-06-03 20:31

from django.db import migrations, models


def assign_codes(apps, schema_editor):
    Product = apps.get_model('catalog', 'Product')
    for product in Product.objects.filter(code=''):
        product.code = f'M2-FIX-{product.pk:05d}'
        product.save(update_fields=['code'])


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_social_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=20, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='product',
            name='qrcode_image',
            field=models.ImageField(blank=True, upload_to='qrcodes/', verbose_name='QR Code'),
        ),
        migrations.RunPython(assign_codes, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='facebook',
            field=models.URLField(blank=True, help_text='URL completa da página', max_length=255, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='instagram',
            field=models.URLField(blank=True, help_text='URL completa do perfil. Ex: https://instagram.com/m.2modamasculina', max_length=255, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='tiktok',
            field=models.URLField(blank=True, help_text='URL completa do perfil', max_length=255, verbose_name='TikTok'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='twitter',
            field=models.URLField(blank=True, help_text='URL completa do perfil', max_length=255, verbose_name='Twitter / X'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='youtube',
            field=models.URLField(blank=True, help_text='URL completa do canal', max_length=255, verbose_name='YouTube'),
        ),
    ]
