# Generated by Django 5.0.14 on 2026-07-30 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_add_purchase_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, default='', max_length=20, verbose_name='Tamanho')),
                ('color', models.CharField(blank=True, default='', max_length=50, verbose_name='Cor')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Estoque')),
                ('sku', models.CharField(blank=True, default='', max_length=50, verbose_name='SKU')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Variação',
                'verbose_name_plural': 'Variações',
                'ordering': ['order', 'size'],
                'unique_together': {('product', 'size', 'color')},
            },
        ),
    ]
