# Generated by Django 5.0.14 on 2026-07-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_product_secondary_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Texto exibido no topo do site. Ex: "🔥 Moda masculina com estilo e atitude"', max_length=200, verbose_name='Frase')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Frase do Ticker',
                'verbose_name_plural': 'Frases do Ticker',
                'ordering': ['order', 'id'],
            },
        ),
    ]
