# Generated by Django 5.0.14 on 2026-06-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Dinheiro'), ('card', 'Cartão'), ('pix', 'PIX'), ('other', 'Outro')], default='cash', max_length=20, verbose_name='Forma de Pagamento'),
        ),
    ]
